package com.yourpackage.controller;

import com.yourpackage.DAO.UserDAO;
import com.yourpackage.Model.User;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

public class SignupController {

    private final UserDAO userDao;

    public SignupController(UserDAO userDao) {
        this.userDao = userDao;
    }

    @FXML
    private TextField usernameField;

    @FXML
    private TextField emailField;

    @FXML
    private PasswordField passwordField;

    @FXML
    private void handleSignUp() {
        String username = usernameField.getText();
        String email = emailField.getText();
        String password = passwordField.getText();

        User newUser = new User(0, username, email, password); // Assuming 0 for the ID, it will be auto-generated by the database

        userDao.add(newUser);

        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle("Sign Up");
        alert.setHeaderText(null);
        alert.setContentText("Sign Up successful!");
        alert.showAndWait();
    }
}